apiVersion: v1
kind: ReplicationController
metadata:
  name: dpr-rep
  labels:
    app: dpr-mockup
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: dpr-mockup
    spec:
      containers:
      - name: server
        image: fanoftal2/dpr:1
        args: ["8080"]
        resources:
        ports:
        - containerPort: 8080

