apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: graphviz
    tier: backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: graphviz
    tier: backend
